service: aws-lambda-puppeteer
provider:
  name: aws
  profile: aws-lambda-puppeteer
  region: ap-northeast-2
  runtime: nodejs14.x

package:
  patterns:
    - "!layers/**"

plugins:
  - serverless-offline
  - serverless-latest-layer-version

functions:
  run:
    handler: handler.run
    environment: ${file(env.json)}
    layers:
      - arn:aws:lambda:ap-northeast-2:104955489769:layer:puppeteer-layer:latest

    memorySize: 800
    timeout: 60
    events:
      - http:
          path: /
          method: get
